### ISSUE TITLE
Fail to build on Ubuntu 22.04 (5.15.0-1028-aws)

### ISSUE THREAD

**Issue by F-WRunTime** [ledgerwatch/erigon#7108]
#### System information

**Erigon version: `./erigon --version`**
Stable  -- v2.40.1 

**OS & Version: Windows/Linux/OSX**
Linux 

**Commit hash:** 
94b4cee5a898a47b9241ce824622af6350e5dc5b

**Erigon Command (with flags/config):**
`make erigon`

#### Expected behaviour
Successful build of erigon 

#### Actual behaviour
Fails with only the following build info about 

#### Steps to reproduce the behaviour
Spin up aws ubunut 22.04 
Install go 1.20 
Clone erigon 
Execute make erigon

#### Backtrace

````
Building erigon
github.com/torquem-ch/mdbx-go/mdbx: build constraints exclude all Go files in /home/ubuntu/go/pkg/mod/github.com/torquem-ch/mdbx-go@v0.27.8/mdbx
github.com/ledgerwatch/erigon-lib/sais: build constraints exclude all Go files in /home/ubuntu/go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/sais
# github.com/anacrolix/go-libutp
../../../go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:9:2: undefined: mu
../../../go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:10:8: undefined: mu
../../../go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/status.go:11:20: undefined: libContextToSocket
# github.com/ledgerwatch/erigon-lib/types
../../../go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/types/txn.go:450:24: undefined: secp256k1.RecoverPubkeyWithContext
../../../go/pkg/mod/github.com/ledgerwatch/erigon-lib@v0.0.0-20230306114514-2c4c92fd1fce/types/txn.go:450:59: undefined: secp256k1.DefaultContext
# github.com/supranational/blst/bindings/go
../../../go/pkg/mod/github.com/supranational/blst@v0.3.10/bindings/go/rb_tree.go:130:18: undefined: Message
make: *** [Makefile:98: erigon.cmd] Error 1
````

**Comment by F-WRunTime** [comment]
Update: 
Working through trying to find a solution. I did not pin point what specifically was causing the issue. 
Fix: 
Downgrade GO: go version go1.19.7 linux/amd64 -- latest release prior to 1.20
